import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./store/storeProvider";
import { Toaster } from "react-hot-toast";
import InitUser from "./initUser";
import ThemeWrapper from "@/components/themeWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TaskHub Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <StoreProvider>
        <ThemeWrapper>
            <InitUser />
            {children}
          </ThemeWrapper>
          </StoreProvider>
          <Toaster
            toastOptions={{
              className: "text-md font-semibold",
              duration: 5000,
            }}
          />
      </body>
    </html>
  );
}
